version: '3'
services:
  db:
    container_name: people-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - people_mysql-data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people

  adminer:
    container_name: mysql-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  people_mysql-data:
